/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ../LiteDTUv2_0_AUTOTMR/1_LDTU_Baseline_subtractionTMR.v                                *
 *                                                                                                  *
 * user    : soldi                                                                                  *
 * host    : elt159xl.to.infn.it                                                                    *
 * date    : 03/03/2021 13:21:37                                                                    *
 *                                                                                                  *
 * workdir : /export/elt159xl/disk0/users/soldi/LiTE-DTU_v2.0_2021_Simulations/pre-synth/LiteDTUv2_0_NoTMR *
 * cmd     : /export/elt159xl/disk0/users/soldi/LiTE-DTU_v2.0_2021_Simulations/tmrg/bin/tmrg -c     *
 *           tmr_Config/Last_DTU_v2.cfg --tmr-dir=../LiteDTUv2_0_AUTOTMR/                           *
 * tmrg rev: ececa199b20e3753893c07f87ef839ce926b269f                                               *
 *                                                                                                  *
 * src file: 1_LDTU_Baseline_subtraction.v                                                          *
 *           File is NOT under version control!                                                     *
 *           Modification time : 2021-02-26 15:51:04.025408                                         *
 *           File Size         : 2436                                                               *
 *           MD5 hash          : 54c7a6d8824d58cd08e2bfa6a650afdc                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`timescale    1ps/1ps
module LDTU_BSTMR(
  DCLK_1,
  DCLK_10,
  rst_bA,
  rst_bB,
  rst_bC,
  DATA12_g01,
  DATA12_g10,
  BSL_VAL_g01,
  BSL_VAL_g10,
  DATA_gain_01,
  DATA_gain_10,
  SeuError
);
parameter    Nbits_12=12;
parameter    Nbits_8=8;
wire DCLK_1C;
wire DCLK_1B;
wire DCLK_1A;
wire [Nbits_12-1:0] DATA12_g10C;
wire [Nbits_12-1:0] DATA12_g10B;
wire [Nbits_12-1:0] DATA12_g10A;
wire [Nbits_12-1:0] DATA12_g01C;
wire [Nbits_12-1:0] DATA12_g01B;
wire [Nbits_12-1:0] DATA12_g01A;
wire DCLK_10C;
wire DCLK_10B;
wire DCLK_10A;
wire [Nbits_8-1:0] BSL_VAL_g10C;
wire [Nbits_8-1:0] BSL_VAL_g10B;
wire [Nbits_8-1:0] BSL_VAL_g10A;
wire [Nbits_8-1:0] BSL_VAL_g01C;
wire [Nbits_8-1:0] BSL_VAL_g01B;
wire [Nbits_8-1:0] BSL_VAL_g01A;
wire tmrError;
wor dg10TmrError;
wor dg01TmrError;
wire [Nbits_12-1:0] dg10;
wire [Nbits_12-1:0] dg01;
input DCLK_1;
input DCLK_10;
input rst_bA;
input rst_bB;
input rst_bC;
input [Nbits_12-1:0] DATA12_g01;
input [Nbits_12-1:0] DATA12_g10;
input [Nbits_8-1:0] BSL_VAL_g01;
input [Nbits_8-1:0] BSL_VAL_g10;
output reg   [Nbits_12-1:0] DATA_gain_01;
output reg   [Nbits_12-1:0] DATA_gain_10;
output SeuError;
wire [Nbits_12-1:0] b_val_g01A;
wire [Nbits_12-1:0] b_val_g01B;
wire [Nbits_12-1:0] b_val_g01C;
wire [Nbits_12-1:0] b_val_g10A;
wire [Nbits_12-1:0] b_val_g10B;
wire [Nbits_12-1:0] b_val_g10C;
reg  [Nbits_12-1:0] d_g01A;
reg  [Nbits_12-1:0] d_g01B;
reg  [Nbits_12-1:0] d_g01C;
reg  [Nbits_12-1:0] d_g10A;
reg  [Nbits_12-1:0] d_g10B;
reg  [Nbits_12-1:0] d_g10C;
wire [Nbits_12-1:0] dg01A;
wire [Nbits_12-1:0] dg01B;
wire [Nbits_12-1:0] dg01C;
wire [Nbits_12-1:0] dg10A;
wire [Nbits_12-1:0] dg10B;
wire [Nbits_12-1:0] dg10C;
assign SeuError =  tmrError;
assign b_val_g01A =  {4'b0,BSL_VAL_g01A};
assign b_val_g01B =  {4'b0,BSL_VAL_g01B};
assign b_val_g01C =  {4'b0,BSL_VAL_g01C};
assign b_val_g10A =  {4'b0,BSL_VAL_g10A};
assign b_val_g10B =  {4'b0,BSL_VAL_g10B};
assign b_val_g10C =  {4'b0,BSL_VAL_g10C};

always @( posedge DCLK_1A )
  begin
    if (rst_bA==1'b0)
      d_g01A <= 12'b0;
    else
      d_g01A <= DATA12_g01A;
  end

always @( posedge DCLK_1B )
  begin
    if (rst_bB==1'b0)
      d_g01B <= 12'b0;
    else
      d_g01B <= DATA12_g01B;
  end

always @( posedge DCLK_1C )
  begin
    if (rst_bC==1'b0)
      d_g01C <= 12'b0;
    else
      d_g01C <= DATA12_g01C;
  end

always @( posedge DCLK_10A )
  begin
    if (rst_bA==1'b0)
      d_g10A <= 12'b0;
    else
      d_g10A <= DATA12_g10A;
  end

always @( posedge DCLK_10B )
  begin
    if (rst_bB==1'b0)
      d_g10B <= 12'b0;
    else
      d_g10B <= DATA12_g10B;
  end

always @( posedge DCLK_10C )
  begin
    if (rst_bC==1'b0)
      d_g10C <= 12'b0;
    else
      d_g10C <= DATA12_g10C;
  end
assign dg01A =  d_g01A-b_val_g01A;
assign dg01B =  d_g01B-b_val_g01B;
assign dg01C =  d_g01C-b_val_g01C;
assign dg10A =  d_g10A-b_val_g10A;
assign dg10B =  d_g10B-b_val_g10B;
assign dg10C =  d_g10C-b_val_g10C;

always @( posedge DCLK_1 )
  begin
    DATA_gain_01 <= dg01;
  end

always @( posedge DCLK_10 )
  begin
    DATA_gain_10 <= dg10;
  end

majorityVoter #(.WIDTH(((Nbits_12-1)>(0)) ? ((Nbits_12-1)-(0)+1) : ((0)-(Nbits_12-1)+1))) dg01Voter (
    .inA(dg01A),
    .inB(dg01B),
    .inC(dg01C),
    .out(dg01),
    .tmrErr(dg01TmrError)
    );

majorityVoter #(.WIDTH(((Nbits_12-1)>(0)) ? ((Nbits_12-1)-(0)+1) : ((0)-(Nbits_12-1)+1))) dg10Voter (
    .inA(dg10A),
    .inB(dg10B),
    .inC(dg10C),
    .out(dg10),
    .tmrErr(dg10TmrError)
    );
assign tmrError =  dg01TmrError|dg10TmrError;

fanout #(.WIDTH(((Nbits_8-1)>(0)) ? ((Nbits_8-1)-(0)+1) : ((0)-(Nbits_8-1)+1))) BSL_VAL_g01Fanout (
    .in(BSL_VAL_g01),
    .outA(BSL_VAL_g01A),
    .outB(BSL_VAL_g01B),
    .outC(BSL_VAL_g01C)
    );

fanout #(.WIDTH(((Nbits_8-1)>(0)) ? ((Nbits_8-1)-(0)+1) : ((0)-(Nbits_8-1)+1))) BSL_VAL_g10Fanout (
    .in(BSL_VAL_g10),
    .outA(BSL_VAL_g10A),
    .outB(BSL_VAL_g10B),
    .outC(BSL_VAL_g10C)
    );

fanout DCLK_10Fanout (
    .in(DCLK_10),
    .outA(DCLK_10A),
    .outB(DCLK_10B),
    .outC(DCLK_10C)
    );

fanout #(.WIDTH(((Nbits_12-1)>(0)) ? ((Nbits_12-1)-(0)+1) : ((0)-(Nbits_12-1)+1))) DATA12_g01Fanout (
    .in(DATA12_g01),
    .outA(DATA12_g01A),
    .outB(DATA12_g01B),
    .outC(DATA12_g01C)
    );

fanout #(.WIDTH(((Nbits_12-1)>(0)) ? ((Nbits_12-1)-(0)+1) : ((0)-(Nbits_12-1)+1))) DATA12_g10Fanout (
    .in(DATA12_g10),
    .outA(DATA12_g10A),
    .outB(DATA12_g10B),
    .outC(DATA12_g10C)
    );

fanout DCLK_1Fanout (
    .in(DCLK_1),
    .outA(DCLK_1A),
    .outB(DCLK_1B),
    .outC(DCLK_1C)
    );
endmodule

