set sdc_version 1.3

set tmrgSucces 0
set tmrgFailed 0
proc constrainNet netName {
  global tmrgSucces
  global tmrgFailed
  # find nets matching netName pattern
  set nets [dc::get_net $netName]
  if {[llength $nets] != 0} {
    set_dont_touch $nets
    incr tmrgSucces
  } else {
    puts "\[TMRG\] Warning! Net(s) '$netName' not found"
    incr tmrgFailed
  }
}

constrainNet /B_subtraction/BSL_VAL_g01A[*]
constrainNet /B_subtraction/BSL_VAL_g01B[*]
constrainNet /B_subtraction/BSL_VAL_g01C[*]
constrainNet /B_subtraction/BSL_VAL_g01[*]
constrainNet /B_subtraction/BSL_VAL_g10A[*]
constrainNet /B_subtraction/BSL_VAL_g10B[*]
constrainNet /B_subtraction/BSL_VAL_g10C[*]
constrainNet /B_subtraction/BSL_VAL_g10[*]
constrainNet /B_subtraction/DATA12_g01A[*]
constrainNet /B_subtraction/DATA12_g01B[*]
constrainNet /B_subtraction/DATA12_g01C[*]
constrainNet /B_subtraction/DATA12_g01[*]
constrainNet /B_subtraction/DATA12_g10A[*]
constrainNet /B_subtraction/DATA12_g10B[*]
constrainNet /B_subtraction/DATA12_g10C[*]
constrainNet /B_subtraction/DATA12_g10[*]
constrainNet /B_subtraction/DCLK_1
constrainNet /B_subtraction/DCLK_10
constrainNet /B_subtraction/DCLK_10A
constrainNet /B_subtraction/DCLK_10B
constrainNet /B_subtraction/DCLK_10C
constrainNet /B_subtraction/DCLK_1A
constrainNet /B_subtraction/DCLK_1B
constrainNet /B_subtraction/DCLK_1C
constrainNet /B_subtraction/dg01A[*]
constrainNet /B_subtraction/dg01B[*]
constrainNet /B_subtraction/dg01C[*]
constrainNet /B_subtraction/dg01[*]
constrainNet /B_subtraction/dg10A[*]
constrainNet /B_subtraction/dg10B[*]
constrainNet /B_subtraction/dg10C[*]
constrainNet /B_subtraction/dg10[*]
constrainNet /CALIBRATION_BUSY
constrainNet /CALIBRATION_BUSYA
constrainNet /CALIBRATION_BUSYB
constrainNet /CALIBRATION_BUSYC
constrainNet /CLK
constrainNet /CLKA
constrainNet /CLKB
constrainNet /CLKC
constrainNet /Control_Unit/DATA_32A[*]
constrainNet /Control_Unit/DATA_32B[*]
constrainNet /Control_Unit/DATA_32C[*]
constrainNet /Control_Unit/DATA_32[*]
constrainNet /Control_Unit/DATA_32_FBA[*]
constrainNet /Control_Unit/DATA_32_FBB[*]
constrainNet /Control_Unit/DATA_32_FBC[*]
constrainNet /Control_Unit/DATA_32_FB[*]
constrainNet /Control_Unit/Load_data
constrainNet /Control_Unit/Load_dataA
constrainNet /Control_Unit/Load_dataB
constrainNet /Control_Unit/Load_dataC
constrainNet /Control_Unit/Load_data_FB
constrainNet /Control_Unit/Load_data_FBA
constrainNet /Control_Unit/Load_data_FBB
constrainNet /Control_Unit/Load_data_FBC
constrainNet /Control_Unit/fallback
constrainNet /Control_Unit/fallbackA
constrainNet /Control_Unit/fallbackB
constrainNet /Control_Unit/fallbackC
constrainNet /Control_Unit/full
constrainNet /Control_Unit/fullA
constrainNet /Control_Unit/fullB
constrainNet /Control_Unit/fullC
constrainNet /Control_Unit/handshake
constrainNet /Control_Unit/handshakeA
constrainNet /Control_Unit/handshakeB
constrainNet /Control_Unit/handshakeC
constrainNet /DATA32_0A[*]
constrainNet /DATA32_0B[*]
constrainNet /DATA32_0C[*]
constrainNet /DATA32_0[*]
constrainNet /DATA32_1A[*]
constrainNet /DATA32_1B[*]
constrainNet /DATA32_1C[*]
constrainNet /DATA32_1[*]
constrainNet /DATA32_2A[*]
constrainNet /DATA32_2B[*]
constrainNet /DATA32_2C[*]
constrainNet /DATA32_2[*]
constrainNet /DATA32_3A[*]
constrainNet /DATA32_3B[*]
constrainNet /DATA32_3C[*]
constrainNet /DATA32_3[*]
constrainNet /DATA32_ATU_0A[*]
constrainNet /DATA32_ATU_0B[*]
constrainNet /DATA32_ATU_0C[*]
constrainNet /DATA32_ATU_0[*]
constrainNet /DATA32_ATU_1A[*]
constrainNet /DATA32_ATU_1B[*]
constrainNet /DATA32_ATU_1C[*]
constrainNet /DATA32_ATU_1[*]
constrainNet /DATA32_ATU_2A[*]
constrainNet /DATA32_ATU_2B[*]
constrainNet /DATA32_ATU_2C[*]
constrainNet /DATA32_ATU_2[*]
constrainNet /DATA32_ATU_3A[*]
constrainNet /DATA32_ATU_3B[*]
constrainNet /DATA32_ATU_3C[*]
constrainNet /DATA32_ATU_3[*]
constrainNet /DATA32_DTUA[*]
constrainNet /DATA32_DTUB[*]
constrainNet /DATA32_DTUC[*]
constrainNet /DATA32_DTU[*]
constrainNet /DATA_from_CUA[*]
constrainNet /DATA_from_CUB[*]
constrainNet /DATA_from_CUC[*]
constrainNet /DATA_from_CU[*]
constrainNet /Encoder/CLK
constrainNet /Encoder/CLKA
constrainNet /Encoder/CLKB
constrainNet /Encoder/CLKC
constrainNet /Encoder/Current_stateA[*]
constrainNet /Encoder/Current_stateB[*]
constrainNet /Encoder/Current_stateC[*]
constrainNet /Encoder/Current_state[*]
constrainNet /Encoder/Current_state_FBA[*]
constrainNet /Encoder/Current_state_FBB[*]
constrainNet /Encoder/Current_state_FBC[*]
constrainNet /Encoder/Current_state_FB[*]
constrainNet /Encoder/DATA_to_encA[*]
constrainNet /Encoder/DATA_to_encB[*]
constrainNet /Encoder/DATA_to_encC[*]
constrainNet /Encoder/DATA_to_enc[*]
constrainNet /Encoder/baseline_flag
constrainNet /Encoder/baseline_flagA
constrainNet /Encoder/baseline_flagB
constrainNet /Encoder/baseline_flagC
constrainNet /Encoder/fallback
constrainNet /Encoder/fallbackA
constrainNet /Encoder/fallbackB
constrainNet /Encoder/fallbackC
constrainNet /Encoder/fsm/CLK
constrainNet /Encoder/fsm/CLKA
constrainNet /Encoder/fsm/CLKB
constrainNet /Encoder/fsm/CLKC
constrainNet /Encoder/fsm/Orbit
constrainNet /Encoder/fsm/OrbitA
constrainNet /Encoder/fsm/OrbitB
constrainNet /Encoder/fsm/OrbitC
constrainNet /Encoder/fsm/baseline_flag
constrainNet /Encoder/fsm/baseline_flagA
constrainNet /Encoder/fsm/baseline_flagB
constrainNet /Encoder/fsm/baseline_flagC
constrainNet /Encoder/fsm/fallback
constrainNet /Encoder/fsm/fallbackA
constrainNet /Encoder/fsm/fallbackB
constrainNet /Encoder/fsm/fallbackC
constrainNet /Encoder/fsm/rCurrent_stateA[*]
constrainNet /Encoder/fsm/rCurrent_stateB[*]
constrainNet /Encoder/fsm/rCurrent_stateC[*]
constrainNet /Encoder/fsm/rCurrent_state[*]
constrainNet /Encoder/fsm/rCurrent_state_FBA[*]
constrainNet /Encoder/fsm/rCurrent_state_FBB[*]
constrainNet /Encoder/fsm/rCurrent_state_FBC[*]
constrainNet /Encoder/fsm/rCurrent_state_FB[*]
constrainNet /Encoder/fsm/rst_b
constrainNet /Encoder/fsm/rst_bA
constrainNet /Encoder/fsm/rst_bB
constrainNet /Encoder/fsm/rst_bC
constrainNet /Encoder/rDATA_32A[*]
constrainNet /Encoder/rDATA_32B[*]
constrainNet /Encoder/rDATA_32C[*]
constrainNet /Encoder/rDATA_32[*]
constrainNet /Encoder/rDATA_32_FBA[*]
constrainNet /Encoder/rDATA_32_FBB[*]
constrainNet /Encoder/rDATA_32_FBC[*]
constrainNet /Encoder/rDATA_32_FB[*]
constrainNet /Encoder/rLoad
constrainNet /Encoder/rLoadA
constrainNet /Encoder/rLoadB
constrainNet /Encoder/rLoadC
constrainNet /Encoder/rLoad_FB
constrainNet /Encoder/rLoad_FBA
constrainNet /Encoder/rLoad_FBB
constrainNet /Encoder/rLoad_FBC
constrainNet /Encoder/rst_b
constrainNet /Encoder/rst_bA
constrainNet /Encoder/rst_bB
constrainNet /Encoder/rst_bC
constrainNet /RD_to_SERIALIZER
constrainNet /RD_to_SERIALIZERA
constrainNet /RD_to_SERIALIZERB
constrainNet /RD_to_SERIALIZERC
constrainNet /RST
constrainNet /RSTA
constrainNet /RSTB
constrainNet /RSTC
constrainNet /Selection/CLK
constrainNet /Selection/CLKA
constrainNet /Selection/CLKB
constrainNet /Selection/CLKC
constrainNet /Selection/DATA_gain_01A[*]
constrainNet /Selection/DATA_gain_01B[*]
constrainNet /Selection/DATA_gain_01C[*]
constrainNet /Selection/DATA_gain_01[*]
constrainNet /Selection/DATA_gain_10A[*]
constrainNet /Selection/DATA_gain_10B[*]
constrainNet /Selection/DATA_gain_10C[*]
constrainNet /Selection/DATA_gain_10[*]
constrainNet /Selection/DCLK_1
constrainNet /Selection/DCLK_10
constrainNet /Selection/DCLK_10A
constrainNet /Selection/DCLK_10B
constrainNet /Selection/DCLK_10C
constrainNet /Selection/DCLK_1A
constrainNet /Selection/DCLK_1B
constrainNet /Selection/DCLK_1C
constrainNet /Selection/GAIN_SEL_MODEA[*]
constrainNet /Selection/GAIN_SEL_MODEB[*]
constrainNet /Selection/GAIN_SEL_MODEC[*]
constrainNet /Selection/GAIN_SEL_MODE[*]
constrainNet /Selection/SATURATION_valueA[*]
constrainNet /Selection/SATURATION_valueB[*]
constrainNet /Selection/SATURATION_valueC[*]
constrainNet /Selection/SATURATION_value[*]
constrainNet /Selection/bsflag
constrainNet /Selection/bsflagA
constrainNet /Selection/bsflagB
constrainNet /Selection/bsflagC
constrainNet /Selection/d2encA[*]
constrainNet /Selection/d2encB[*]
constrainNet /Selection/d2encC[*]
constrainNet /Selection/d2enc[*]
constrainNet /Selection/rst_b
constrainNet /Selection/rst_bA
constrainNet /Selection/rst_bB
constrainNet /Selection/rst_bC
constrainNet /Selection/shift_gain_10A[*]
constrainNet /Selection/shift_gain_10B[*]
constrainNet /Selection/shift_gain_10C[*]
constrainNet /Selection/shift_gain_10[*]
constrainNet /StorageFIFO/CLK
constrainNet /StorageFIFO/CLKA
constrainNet /StorageFIFO/CLKB
constrainNet /StorageFIFO/CLKC
constrainNet /StorageFIFO/FIFO/CLK
constrainNet /StorageFIFO/FIFO/CLKA
constrainNet /StorageFIFO/FIFO/CLKB
constrainNet /StorageFIFO/FIFO/CLKC
constrainNet /StorageFIFO/FIFO/data_inputA[*]
constrainNet /StorageFIFO/FIFO/data_inputB[*]
constrainNet /StorageFIFO/FIFO/data_inputC[*]
constrainNet /StorageFIFO/FIFO/data_input[*]
constrainNet /StorageFIFO/FIFO/full_signal
constrainNet /StorageFIFO/FIFO/full_signalA
constrainNet /StorageFIFO/FIFO/full_signalB
constrainNet /StorageFIFO/FIFO/full_signalC
constrainNet /StorageFIFO/FIFO/ptr_readA[*]
constrainNet /StorageFIFO/FIFO/ptr_readB[*]
constrainNet /StorageFIFO/FIFO/ptr_readC[*]
constrainNet /StorageFIFO/FIFO/ptr_read[*]
constrainNet /StorageFIFO/FIFO/ptr_writeA[*]
constrainNet /StorageFIFO/FIFO/ptr_writeB[*]
constrainNet /StorageFIFO/FIFO/ptr_writeC[*]
constrainNet /StorageFIFO/FIFO/ptr_write[*]
constrainNet /StorageFIFO/FIFO/rst_b
constrainNet /StorageFIFO/FIFO/rst_bA
constrainNet /StorageFIFO/FIFO/rst_bB
constrainNet /StorageFIFO/FIFO/rst_bC
constrainNet /StorageFIFO/FIFO/start_write
constrainNet /StorageFIFO/FIFO/start_writeA
constrainNet /StorageFIFO/FIFO/start_writeB
constrainNet /StorageFIFO/FIFO/start_writeC
constrainNet /StorageFIFO/data_in_38A[*]
constrainNet /StorageFIFO/data_in_38B[*]
constrainNet /StorageFIFO/data_in_38C[*]
constrainNet /StorageFIFO/data_in_38[*]
constrainNet /StorageFIFO/data_out_32A[*]
constrainNet /StorageFIFO/data_out_32B[*]
constrainNet /StorageFIFO/data_out_32C[*]
constrainNet /StorageFIFO/data_out_32[*]
constrainNet /StorageFIFO/decode_signal
constrainNet /StorageFIFO/decode_signalA
constrainNet /StorageFIFO/decode_signalB
constrainNet /StorageFIFO/decode_signalC
constrainNet /StorageFIFO/read_signal
constrainNet /StorageFIFO/read_signalA
constrainNet /StorageFIFO/read_signalB
constrainNet /StorageFIFO/read_signalC
constrainNet /StorageFIFO/rst_b
constrainNet /StorageFIFO/rst_bA
constrainNet /StorageFIFO/rst_bB
constrainNet /StorageFIFO/rst_bC
constrainNet /StorageFIFO/start_write
constrainNet /StorageFIFO/start_writeA
constrainNet /StorageFIFO/start_writeB
constrainNet /StorageFIFO/start_writeC
constrainNet /TEST_ENABLE
constrainNet /TEST_ENABLEA
constrainNet /TEST_ENABLEB
constrainNet /TEST_ENABLEC
constrainNet /full
constrainNet /fullA
constrainNet /fullB
constrainNet /fullC
constrainNet /losing_data
constrainNet /losing_dataA
constrainNet /losing_dataB
constrainNet /losing_dataC
constrainNet /reset
constrainNet /resetA
constrainNet /resetB
constrainNet /resetC
constrainNet /write_signal
constrainNet /write_signalA
constrainNet /write_signalB
constrainNet /write_signalC


    puts "TMRG successful  $tmrgSucces failed $tmrgFailed"
